### ISSUE TITLE
Fastmech fails to initialize without CGNS file

### ISSUE THREAD

**Issue by mdpiper** [csdms-contrib/fastmech#9]
Attempting to initialize Fastmech through its BMI without a config file (pointing to a CGNS file of model information) results in a segfault.

This isn't a great reproduce case, but to see this behavior, uncomment the second half of `initialize_test.f90`, then compile and run it; e.g.:
```
mkdir -p _build && cd _build
cmake ..
make
cd test
./initialize_test
```

The output from the second half of the test program:
```
 Initialize with model defaults

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f776b70927f in ???
#1  0x7f776bc6438c in ???
#2  0x7f776bc50208 in ???
#3  0x55918cad7f19 in ???
#4  0x55918cad7070 in ???
#5  0x7f776b6f53d4 in ???
#6  0x55918cad70a0 in ???
	at ../sysdeps/x86_64/elf/start.S:103
Segmentation fault (core dumped)
```

The problem must lie downstream of Fastmech's `initialize_from_defaults` method, but I haven't taken the time to figure out exactly where.

**Comment by mdpiper** [comment]
Fixed by @rmcd-mscb in 94d3c207b2416772d39fa93caf374ae8fc073b8a.
